bindPort = 7000

allowPorts = [
  { single = 80 }, # webdav
  { single = 2080 }, # sftpgo webui
  { single = 6022 }, # homelab ssh
  { single = 18080 }, # qbt webui
  { single = 18081 }, # qbt webui, homelab
]
