- Find Me:
  - Linktree:
    - icon: https://linktr.ee/favicon.ico
      href: https://linktr.ee/purple4pur
  - GitHub:
    - icon: github
      href: https://github.com/purple4pur
  - Bilibili:
    - icon: bilibili
      href: https://space.bilibili.com/68143353
  - X:
    - icon: x
      href: https://x.com/Purple4pur
  - Steam:
    - icon: steam
      href: https://steamcommunity.com/id/purple4pur
  - osu!:
    - icon: osu
      href: https://osu.ppy.sh/users/19433402
- Quick Links:
  - umami:
    - icon: umami
      href: https://cloud.umami.is/
  - Proxy Usage:
    - icon: clash
      href: https://static.quitw.org/dashboard/
