title: Purple4pur's HomePage
background: https://static.quitw.org/img/137292910_p0.small.jpg
cardBlur: xl
favicon: https://static.quitw.org/img/pfp.small.jpg
theme: light
color: white
disableCollapse: true
useEqualHeights: true
headerStyle: boxed
target: _blank
logpath: /app/logs
